<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_69a99cbe03b51',
    'title' => __('Sponsor Offering', 'api-sponsor-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_69a99cbe05b04',
            'label' => __('Assignment Description', 'api-sponsor-manager'),
            'name' => 'description',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        1 => array(
            'key' => 'field_69a99cbe05b52',
            'label' => __('Assignment Image', 'api-sponsor-manager'),
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),
        2 => array(
            'key' => 'field_69a99cbe05b9e',
            'label' => __('Assignment Date', 'api-sponsor-manager'),
            'name' => 'date',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'd/m/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
            'default_to_current_date' => 0,
            'allow_in_bindings' => 0,
        ),
        3 => array(
            'key' => 'field_69a99cbe05beb',
            'label' => __('Assignment Time', 'api-sponsor-manager'),
            'name' => 'time',
            'aria-label' => '',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'H:i:s',
            'return_format' => 'H:i:s',
            'allow_in_bindings' => 0,
        ),
        4 => array(
            'key' => 'field_69a99cbe05c39',
            'label' => __('Assignment Due Date', 'api-sponsor-manager'),
            'name' => 'due_date',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'd/m/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
            'default_to_current_date' => 0,
            'allow_in_bindings' => 0,
        ),
        5 => array(
            'key' => 'field_69a99cbe05c84',
            'label' => __('Assignment Due Time', 'api-sponsor-manager'),
            'name' => 'due_time',
            'aria-label' => '',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'H:i:s',
            'return_format' => 'H:i:s',
            'allow_in_bindings' => 0,
        ),
        6 => array(
            'key' => 'field_69a99cbe05cd0',
            'label' => __('Assignment Location', 'api-sponsor-manager'),
            'name' => 'location',
            'aria-label' => '',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '',
            'center_lng' => '',
            'zoom' => '',
            'height' => '',
            'allow_in_bindings' => 0,
        ),
        7 => array(
            'key' => 'field_69a99cbe05d1a',
            'label' => __('Assignment resources', 'api-sponsor-manager'),
            'name' => 'resources',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'resource',
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
        8 => array(
            'key' => 'field_69a99cbe05d65',
            'label' => __('Assignment activities', 'api-sponsor-manager'),
            'name' => 'activities',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'activity',
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'offering',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 1,
    'display_title' => '',
));
}