<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_69bbaf273446a',
    'title' => __('Notifications', 'api-sponsor-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_69bbaf272549d',
            'label' => __('notification_email_templates', 'api-sponsor-manager'),
            'name' => 'notification_email_templates',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_69bbafbc254a0',
            'button_label' => __('Add Row', 'api-sponsor-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_69bbaf352549e',
                    'label' => __('post_type', 'api-sponsor-manager'),
                    'name' => 'post_type',
                    'aria-label' => '',
                    'type' => 'posttype_select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                    'parent_repeater' => 'field_69bbaf272549d',
                ),
                1 => array(
                    'key' => 'field_69bbaf612549f',
                    'label' => __('trigger', 'api-sponsor-manager'),
                    'name' => 'trigger',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'submit' => __('Submit', 'api-sponsor-manager'),
                        'publish' => __('Publish', 'api-sponsor-manager'),
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                    'parent_repeater' => 'field_69bbaf272549d',
                ),
                2 => array(
                    'key' => 'field_69bbb006254a1',
                    'label' => __('recipients', 'api-sponsor-manager'),
                    'name' => 'recipients',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69bbaf272549d',
                ),
                3 => array(
                    'key' => 'field_69bbafbc254a0',
                    'label' => __('subject', 'api-sponsor-manager'),
                    'name' => 'subject',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69bbaf272549d',
                ),
                4 => array(
                    'key' => 'field_69bbb02c254a2',
                    'label' => __('message', 'api-sponsor-manager'),
                    'name' => 'message',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_69bbaf272549d',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'api-sponsor-manager-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));
}