<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_69a99cbe03b51',
    'title' => __('Sponsor Offering', 'api-sponsor-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_69a99cbe05b52',
            'label' => __('Image', 'api-sponsor-manager'),
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),
        1 => array(
            'key' => 'field_69a99cbe05b9e',
            'label' => __('Date', 'api-sponsor-manager'),
            'name' => 'date',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'Y-m-d',
            'return_format' => 'Y-m-d',
            'first_day' => 1,
            'default_to_current_date' => 0,
            'allow_in_bindings' => 0,
        ),
        2 => array(
            'key' => 'field_69a99cbe05beb',
            'label' => __('Time', 'api-sponsor-manager'),
            'name' => 'time',
            'aria-label' => '',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'H:i:s',
            'return_format' => 'H:i:s',
            'allow_in_bindings' => 0,
        ),
        3 => array(
            'key' => 'field_69a99cbe05cd0',
            'label' => __('Location', 'api-sponsor-manager'),
            'name' => 'location',
            'aria-label' => '',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '',
            'center_lng' => '',
            'zoom' => '',
            'height' => '',
            'allow_in_bindings' => 0,
        ),
        4 => array(
            'key' => 'field_69a99cbe05d1a',
            'label' => __('Resources', 'api-sponsor-manager'),
            'name' => 'resources',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'resource',
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
        5 => array(
            'key' => 'field_69a99cbe05b04',
            'label' => __('Offering Description', 'api-sponsor-manager'),
            'name' => 'description',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        6 => array(
            'key' => 'field_6a9fe4eaa3dcf',
            'label' => __('Requirements', 'api-sponsor-manager'),
            'name' => 'requirements',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Any requirements the association may have, e.g. that the sponsored party works with the UN Sustainable Development Goals, the Convention on the Rights of the Child, or similar', 'api-sponsor-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
        ),
        7 => array(
            'key' => 'field_6a9fec854580c',
            'label' => __('Proposal for “counter-performance” from the association', 'api-sponsor-manager'),
            'name' => 'proposal_for_counter_performance',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
        ),
        8 => array(
            'key' => 'field_69a99cbe05d65',
            'label' => __('Activities', 'api-sponsor-manager'),
            'name' => 'activities',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'activity',
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
        9 => array(
            'key' => 'field_6a9fe576d1768',
            'label' => __('Tags', 'api-sponsor-manager'),
            'name' => 'tags',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('#ALLA #SCOUTERNA etc (se här)', 'api-sponsor-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'post_tag',
            'add_term' => 1,
            'save_terms' => 0,
            'load_terms' => 1,
            'return_format' => 'id',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
        10 => array(
            'key' => 'field_69a99cbe05c39',
            'label' => __('Due Date', 'api-sponsor-manager'),
            'name' => 'due_date',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'Y-m-d',
            'return_format' => 'Y-m-d',
            'first_day' => 1,
            'default_to_current_date' => 0,
            'allow_in_bindings' => 0,
        ),
        11 => array(
            'key' => 'field_69a99cbe05c84',
            'label' => __('Due Time', 'api-sponsor-manager'),
            'name' => 'due_time',
            'aria-label' => '',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'H:i:s',
            'return_format' => 'H:i:s',
            'allow_in_bindings' => 0,
        ),
        12 => array(
            'key' => 'field_6a9fe3b795c7b',
            'label' => __('Preferred Contact Method', 'api-sponsor-manager'),
            'name' => 'contact_method',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'mail' => __('Mail', 'api-sponsor-manager'),
                'phone' => __('Phone', 'api-sponsor-manager'),
            ),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'multiple' => 1,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'offering',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 1,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
));
}